//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Orders = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int UserID { get; set; }
        //[Required]
        //[Display(Name ="User First Name")]
        //[StringLength(50,ErrorMessage ="First Name must be in 50 letters")]
        public string UserFirstName { get; set; }
        //[Required]
        //[Display(Name = "User Last Name")]
        //[StringLength(50, ErrorMessage = "Last Name must be in 50 letters")]
        public string UserLastName { get; set; }
        //[Required]
        //[RegularExpression(".+\\@.+\\..+",ErrorMessage ="Please enter a valid email address")]
        public string UserEmail { get; set; }
        //[Required]
        public string UserPassword { get; set; }
        //[Required]
        //[Display(Name = "User Address")]
        public string UserAddress { get; set; }
        //[Required]
        //[Display(Name = "User Phone No")]
        //[StringLength(11, ErrorMessage = "Last Name must be in 11 letters")]
        public string UserPhoneNo { get; set; }
        //[Required]
        //[Compare("UserPassword")]
        public string ConfirmUserPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
